language: python
python:
  - "3.6"
  - "3.7"
  - "3.8"
dist: xenial     # https://github.com/travis-ci/travis-ci/issues/9069#issuecomment-425720905
install:
  - travis_retry pip install -r test/requirements.txt
  - travis_retry pip install git+https://github.com/slimta/python-slimta.git
  - travis_retry pip install coveralls
  - travis_retry pip install -e .
script: py.test --cov=slimta
after_success:
  - coveralls
